### ISSUE TITLE
SEO Analysis

### ISSUE THREAD

**Issue by ctspukar** [ctspukar/VVMS-Scrum-Sprint#10]
Site: http://www.tmtmaldives.com/

Give me your detailed report on Keywords that you think are important for this business And also list out Action Plan by which mean: what are the steps we will take in first month of our SEO work.

**Comment by sajan9869** [comment]
I studied about tmtmaldives.com website and I am researching on the keywords for SEO work.

**Comment by sajan9869** [comment]
[Seo Analysis.docx](https://github.com/ctspukar/VVMS-Scrum-Sprint/files/1227874/Seo.Analysis.docx)
[report on tmtmaldieves website.docx](https://github.com/ctspukar/VVMS-Scrum-Sprint/files/1227878/report.on.tmtmaldieves.website.docx)

**Comment by sajan9869** [comment]
I have done this much seo analysis on tmtmaldives.com site.

**Comment by ctspukar** [comment]
@sajan9869 Thanks for doing the initial work. I will need much more detail analysis on it. 
Some of the things to consider, who are my competitors and also the keywords that are popular for Maldives travel.  Where is the current standing of tmtmaldives.com when searched for that keywords and where my competitors stand. Please give me a detailed report. 
@santosh-kumar-thapa, help him with anything he needs. Your this work is most important piece either to get the business or not. So please spent some time and do as much research as you can.

**Comment by sajan9869** [comment]
[Seo Analysis.docx](https://github.com/ctspukar/VVMS-Scrum-Sprint/files/1231140/Seo.Analysis.docx)

**Comment by sajan9869** [comment]
I have done SEO analysis on www.tmtmaldives.com. Please, let me know if any information are missing. Thank you

**Comment by ctspukar** [comment]
@sajan9869 & @santosh-kumar-thapa, This is a good start but it needs more work. I am providing you some sites which can help you generate reports and actually compare other competitors on many factors of site.  Please spent some time doing the research and @santosh-kumar-thapa  guide him. 
You will find many many sites like below. Thanks 
https://www.internetmarketingninjas.com/seo-tools/seo-compare/
https://www.internetmarketingninjas.com/seo-tools/robots-txt-generator/
https://www.internetmarketingninjas.com/social-activity-tool/
https://www.internetmarketingninjas.com/pagespeed/
https://www.internetmarketingninjas.com/meta-tag-generator/
https://www.internetmarketingninjas.com/header-checker/
https://www.internetmarketingninjas.com/search/

http://tools.seobook.com/general/keyword-density/
http://microstockgroup.com/tools/keywordcompare.html
http://www.aleydasolis.com/en/search-engine-optimization/keywords-research-tools-comparison/

**Comment by nischalcts** [comment]
[Search-Engine-Optimization-Starter-Guide.pdf](https://github.com/ctspukar/VVMS-Scrum-Sprint/files/1231296/Search-Engine-Optimization-Starter-Guide.pdf)
For the same effort, I have attached a PDF which will point you towards what needs to be done. It is basic but will guide you in right direction. @sajan9869

**Comment by sajan9869** [comment]
I have analyze the pdf file for search engine optimization today and researched on different sites that was given by pukar dai.

**Comment by ctspukar** [comment]
@sajan9869 where is the report ?
