### ISSUE TITLE
Maple-Website- Final Correction

### ISSUE THREAD

**Issue by nischalcts** [ctspukar/VVMS-Scrum-Sprint#2]
Requirements from Customer (Maple) 
1. Down below the banner page we have tab like representing institutions, travel assistance, accommodation assistance, visa documentation, visa interview preparation), make this tabs editable so that i can change image and title in the tab myself. Keep some effects in the tab when cursor points it.

**Comment by santosh-kumar-thapa** [comment]
done

**Comment by nischalcts** [comment]
ctswebhost.webfactional.com/mapletest/?page_id=1357
