### ISSUE TITLE
FTP user for http://adanlock.com/ & http://ssdtinc.com/

### ISSUE THREAD

**Issue by ctspukar** [ctspukar/VVMS-Scrum-Sprint#70]
Can we have a user created just for this application ? Sailesh did similar thing for Insurance project. Look for his help if needed.

**Comment by ctspukar** [comment]
Check this out : May be this will help. 

https://docs.webfaction.com/xmlrpc-api/index.html?highlight=api#webfaction-api-documentation

**Comment by pprabal** [comment]
I tried today with the ftp user of ssdtinc giving all ( read,write and execute) permission. But it is not working. Still trying to figure it out. Also called out support for this.
